apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{ template "flaskcounter.fullname" . }}
  name: {{ template "flaskcounter.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      run: {{ template "flaskcounter.fullname" . }}
  template:
    metadata:
      labels:
        run: {{ template "flaskcounter.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: {{ template "flaskcounter.fullname" . }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        env:
          - name: REDIS_HOST
            value: {{ .Release.Name }}-redis-master
          - name: MYSQL_USER
            value: root
          - name: MYSQL_HOST
            value: mysql-pv-svc
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-redis
                key: redis-password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: password
        resources:
{{ toYaml .Values.resources | indent 10 }}
          
status: {}
