apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ template "flaskcounter.fullname" . }}
  name: {{ template "flaskcounter.fullname" . }}
spec:
  ports:
  - port: {{ .Values.portflask }}
    protocol: TCP
    targetPort: {{ .Values.portflask }}
  selector:
    run: {{ template "flaskcounter.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
