apiVersion: v1
kind: Service
metadata:
  name: mysql-pv-svc
  labels:
    app: {{ template "flaskcounter.fullname" . }}
spec:
  ports:
    - port: {{ .Values.portmysql }}
      protocol: TCP
      targetPort: {{ .Values.portmysql }}
  selector:
    app: {{ template "flaskcounter.fullname" . }}
    tier: mysql-counter
  type: ClusterIP